# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwicIOV6LvWPQqsdTrtmRb_kv9Zv92Ep
"""

import streamlit as st
from youtube_transcript_api import YouTubeTranscriptApi
from gensim.summarization import summarize

# Function to get YouTube video transcript
def get_transcript(video_url):
    video_id = video_url.split('=')[1]
    transcript = YouTubeTranscriptApi.get_transcript(video_id)

    text = ''
    for line in transcript:
        text += ' ' + line['text']

    return text

# Function to summarize text
def get_summary(text):
    summary = summarize(text)
    return summary

# Streamlit app
st.title("YouTube Video Transcription and Summarization")

video_url = st.text_input("Enter YouTube Video URL:")

if video_url:
    st.write("Loading transcription...")
    try:
        transcript = get_transcript(video_url)
        st.write("Transcription:")
        st.text(transcript)

        st.write("Summarizing...")
        summary = get_summary(transcript)
        st.write("Summary:")
        st.text(summary)

    except Exception as e:
        st.write("Error: Unable to fetch transcription.")